Feature: Item-specific Stack Sizes [Part 1/10 of Item Stack Size (formerly #694, formerly restoring #468)]
hannibal002/SkyHanni pull request #759
Opened 2023-12-04 17:22 UTC by RayDeeUx

hanni wanted me to split #694 so here we are. ignore the commit count, this is the only way i could split things without cut and paste abuse

2023-12-04 17:29 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/ItemStars.kt
The change from `CRIMSON_ARMOR.isSelected()` to     `!SkyHanniMod.feature.inventory.stackSize.itemNumber.contains(StackSizeConfig.ItemNumber.CRIMSON_STARS)` does feel like a downgrade

2023-12-04 17:37 UTC, RayDeeUx commented on src/main/java/at/hannibal2/skyhanni/features/inventory/ItemStars.kt
quoting directly from my own discord msgs (which, yes, that means missing punctuation and occasionally poor phrasing):
> it only feels like a downgrade because isselected relies on importing individual members of the enum, and with your ban on star imports id rather be consistent across all the class files while saving on number of import lines
> tldr isselected is wack id rather just do old-fashioned .contains() for consistency

2023-12-04 18:06 UTC, hannibal002 requested changes
The history of a file you moved gets lost entirely, the whole item stack list gets reset in the config, and many lines aren't readable at all. You can add the additional information about the enum instances as comments so we can include it once we have a "hover over to view description" logic.

https://github.com/hannibal002/SkyHanni/pull/755 will be merged first. You might want to wait for this to happen before changing stuff in `ItemDisplayOverlayFeatures`. Or merge walkers changes into your PR, so you can start changing the file right now.

2023-12-04 18:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
> +    fun isRewardChest(): Boolean {
What kind of reward chest is this? either belogs in invenotry utils or inside cata api

2023-12-04 18:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
> +    fun ItemStack.getYetiRodFishesCaught() = getAttributeInt("fishes_caught")
Are we sure this stat is only on the yeti rod?

2023-12-04 18:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/CachedItemData.kt
> +    /** -1 = not loaded */ var auctionNumber: Int? = -1,
please use the same formatting as in the rest of the file

2023-12-04 18:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/utils/SkyBlockItemModifierUtils.kt
> +    }// = getAttributeInt("edition")
Those 2 comments can go

2023-12-04 18:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/SkyHanniMod.kt
> +        loadModule(ItemDisplayOverlayFeatures())
Any particular reason why the object got changed back to a class?

2023-12-04 18:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/inventory/itemdisplayoverlay/ItemDisplayOverlayFeatures.kt
> +class ItemDisplayOverlayFeatures {
Can you make this class not "new" but rather "moved from to"? Otherwise we will lose the whole git history of the file.

2023-12-04 18:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/stacksize/StackSizeConfig.java
> +        ItemNumber.MASTER_STAR,
This list does not get migrated correctly. I just have the default things enabled when testing with a legacy config. This should not happen

2023-12-04 18:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/stacksize/StackSizeConfig.java
> +        MASTER_STAR("§bMaster Star Tier", 0),
Why are you changing almost all the names of the enums?

2023-12-04 18:06 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/config/features/inventory/stacksize/StackSizeConfig.java
> +        JYRRE("§bBottle of Jyrre (#, Intelligence Bonus on Legacy Bottles and Time on New Bottles)", 15),
name too long, can be removed entirely. time on new bottles has nothing to do with this feature, should it's own feature.

2023-12-04 18:08 UTC, RayDeeUx commented on src/main/java/at/hannibal2/skyhanni/utils/LorenzUtils.kt
> +    fun isRewardChest(): Boolean {
https://discord.com/channels/997079228510117908/1153406580621066301/1155039211674685450

2024-01-13 08:57 UTC, CalMWolfs requested changes
ok so much better than i thought it would be (sorry) but my main problem is with the names of variables and functions. While descriptive they seem too long (and too descriptive) which makes the code less readable.
also the base key group along with the individual pattern keys should also be shortened a bit but also split into more words split by fullstops instead of it being like 2 sets of 3-4 words separated by a fullstop

2024-01-13 14:49 UTC, RayDeeUx commented
> but my main problem is with the names of variables and functions. 

i'm content with renaming the variables, but for functions, a good chunk of it is modeled off of @walkerselby's PR #755:
```kt
return when {
    isMasterStar(internalName) -> getMasterStarTip(internalName)
    isMasterSkull(internalName) -> getMasterSkullTip(internalName)
    isDungeonHead(internalName) -> getDungeonHeadTip(internalName)
    isNewYearCake(internalName) -> getNewYearCakeTip(item)
    isPet(itemName) -> getPetTip(itemName)
    isMinionTier(itemName, item) -> getMinionTierTip(itemName)
    isSack(item) -> getSackTip(itemName)
    isKuudraKey(internalName) -> getKuudraKeyTip(internalName)
    isSkillLevel(item) -> getSkillLevelTip(item, itemName)
    isCollectionLevel() -> getCollectionLevelTip(item)
    isRanchersBoots(internalName) -> getRanchersBootsTip(item)
    isLarvaHook(internalName) -> getLarvaHookTip(item)
    isDungeonPotion(item, internalName) -> getDungeonPotionTip(item)
    isVacuumGarden(item) -> getVacuumGardenTip(item)
    isBottleOfJyrre(item) -> getBottleOfJyrreTip(item)
    isEditionNumber(item) -> getEditionNumberTip(item)
    isBingoGoalRank(chestName, item) -> getBingoGoalRankTip(item)
    else -> ""
}
```
this particular PR is supposed to carry that torch, so to speak. if you still want me to rename the functions i can start with removing the `Tip` suffix from most of the functions

also side note: i have't gotten around to using the `return when` statement like walker did for PRs #760 through #768

2024-01-13 16:19 UTC, CalMWolfs commented
Looked at the function names and while they are long it's ok but please do change the variable names

2024-03-11 18:01 UTC, closed without merging