Feature: Crystal Hollows Server Age Warning
hannibal002/SkyHanni pull request #902
Opened 2024-01-11 03:26 UTC by RayDeeUx

impl of below.
<img src="https://github.com/hannibal002/SkyHanni/assets/51521765/c9121a45-0cfc-4619-8e48-c14130037906">

2024-01-11 07:09 UTC, CalMWolfs requested changes

2024-01-11 07:09 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +        if (config.lobbyAgeReminders && !lobbyIsPastAgeThreshold) LorenzUtils.chat("§aThis Crystal Hollows lobby is currently at Day $lobbyAge, ${abs(config.minLobbyAgeThreshold - lobbyAge)} day(s) a
could use `StringUtils.optionalPlural` here

2024-01-11 07:09 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/CrystalHollowsLobbyAgeWarningConfig.java
> +    @FeatureToggle
this doesnt need to be a feature toggle

2024-01-11 07:09 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/CrystalHollowsLobbyAgeWarningConfig.java
> +    @FeatureToggle
same here

2024-01-11 07:09 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/CrystalHollowsLobbyAgeWarningConfig.java
> +}
this is why we have a repo, with the repo they can wait the up to 24hrs for up to 3 numbers being changed.
These should not be included as hidden config elements like this

2024-01-11 07:09 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +                else LorenzUtils.chat("There are $playerCount players remaining in this Crystal Hollows lobby. §cIt will shut down when there are fewer than ${config.minPlayers} people left, or when
i feel the `whichever happens first` is unneeded

2024-01-11 07:09 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +    private val config get() = SkyHanniMod.feature.mining.crystalHollowsLobbyAgeWarning
i feel most of our code has the config variable at the top of the file not the bottom

2024-01-11 07:09 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +    private val TICKS_PER_MC_DAY_MINECRAFT: Long = 24000L
dont think this needs mc and minecraft in the same const name

2024-01-11 07:09 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +    private val playerCountTabListPattern by crystalHollowsLobbyRepoGroup.pattern(("playercount.tablist"), (" *(?:§.)*Players[\\S ]*[\\(\\[\\{](?<playerCount>[\\S ]+)[\\)\\]\\}]"))
not sure if we need the group here as its only 1 pattern
also there seems to be extra sets of brackets in the .pattern
also up to you but if you format these lines more like i have in https://github.com/hannibal002/SkyHanni/pull/871 (naming of group if you still want it and formatting of the pattern line itself) that would be cool

2024-01-11 07:14 UTC, CalMWolfs commented
also forgot to say lots of somewhat random comments that seem a little unnecessary
was also goign to say that i dont think you can add desciptions for the config categories but ur weird way of storing config values crashes me anyways https://hst.sh/ovifufebad

2024-01-12 00:42 UTC, RayDeeUx commented on src/main/java/at/hannibal2/skyhanni/config/features/mining/CrystalHollowsLobbyAgeWarningConfig.java
> +}
done, see hannibal002/SkyHanni-REPO#93

2024-01-14 06:43 UTC, CalMWolfs requested changes
still not sure what race condition those comments are reffering to (and also dont really need to know) but you check if in crystal hollows twice. Once when calling isEnabled and once in the other function. Once one of those is removed then this is looking good (also prob dont need the race condition comments)

2024-01-16 03:09 UTC, RayDeeUx commented
should mention: the race condition is that it'll (sometimes) send a chat message on player count (and presumably server day, but player count changes more often) when you go to dwarven mines

2024-01-18 20:19 UTC, CalMWolfs requested changes
a few more code cleanup things

2024-01-18 20:19 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +    private val playerCountTabListPattern by crystalHollowsLobbyRepoGroup.pattern(
```suggestion
    private val patternGroup = RepoPattern.group("mining.crystalhollows.lobbyage")
    private val playerCountTabListPattern by patternGroup.pattern(
```

2024-01-18 20:19 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +    private fun isEnabled() = config.enabled
```suggestion
    private fun isEnabled() = THE_CRYSTAL_HOLLOWS.isInIsland() && config.enabled
```

and then can remove all other checks in the code for being in skyblock and in the crystal hollows

2024-02-18 06:11 UTC, CalMWolfs requested changes
changes

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +        " *(?:§.)*Players[\\S ]*[({\\[](?<playerCount>[\\S ]+)[)}\\]]"
```suggestion
        "\\s+(?:§.)+Players\\s+(?:§.)+\\((?<playerCount>\\d+)\\)"
```

this should be better

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +    }
why new function

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +                else LorenzUtils.chat("There are $playerCount players remaining in this Crystal Hollows lobby. §cIt will shut down when there are fewer than $minPlayers people left, or when this lobb
```suggestion
                else LorenzUtils.chat("There are $playerCount players remaining in this Crystal Hollows lobby. §cIt will shut down when there are fewer than $minPlayers people left, or when this lobby reaches Day $maxLobbyAgeMCDays.")
                return
```

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +    private fun getLobbyAgeInMinecraftDays(): Long = (mc.theWorld.worldTime) / TICKS_PER_MC_DAY //world day changes at 6AM in skyblock time
This shouldnt be a long

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +    private var minPlayers: Int = 4
Why are these longs

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +    private val mc get() = Minecraft.getMinecraft()
no

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +        if (event.newIsland != THE_CRYSTAL_HOLLOWS) {
why not just reset on any island change?

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +        maxLobbyAgeMCDays = data.maxLobbyAgeMCDays
```suggestion
        minLobbyAge = data.minLobbyAge
        maxLobbyAge = data.maxLobbyAge
```
Dont need to specify that

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +        } else if (lobbyAge >= maxLobbyAgeMCDays) LorenzUtils.chat("§cThis Crystal Hollows lobby has reached Day $maxLobbyAgeMCDays. §4§lIt will shut down very soon.")
This is unreadable also use this https://github.com/hannibal002/SkyHanni/pull/975

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +    private fun getLobbyAgeInMinecraftDays(): Long = (mc.theWorld.worldTime) / TICKS_PER_MC_DAY //world day changes at 6AM in skyblock time
also should be called getLobbyAge

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +                val playerCount = group("playerCount").formatNumber()
Can just use .toInt()

2024-02-18 06:11 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +                else LorenzUtils.chat("There are $playerCount players remaining in this Crystal Hollows lobby. §cIt will shut down when there are fewer than $minPlayers people left, or when this lobb
this is also confusing and long and idk

2024-03-09 22:56 UTC, hannibal002 requested changes

2024-03-09 22:56 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/mining/crystalhollows/CrystalHollowsLobbyAgeWarning.kt
> +        if (config.lobbyAgeReminders && !lobbyIsPastAgeThreshold) LorenzUtils.chat("§aThis Crystal Hollows lobby is currently at Day $lobbyAge, ${StringUtils.optionalPlural(number = abs(minLobbyAgeMC
`StringUtils.optionalPlural` does no longer exist

2024-04-04 00:28 UTC, closed without merging