Feature: Volcano Explosivity Display
hannibal002/SkyHanni pull request #937
Opened 2024-01-18 03:32 UTC by RayDeeUx

impl of below.
<img src="https://github.com/hannibal002/SkyHanni/assets/51521765/dd8a572c-9ea4-4be7-b808-74776734266f">

![](https://github.com/hannibal002/SkyHanni/assets/51521765/00515880-24e2-4ce7-9146-3142b16a4d12)

(i have since then made the prefix text blue and kept colon as `§7`)

2024-01-18 07:13 UTC, CalMWolfs requested changes

2024-01-18 07:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +    @SubscribeEvent
missing empty line

2024-01-18 07:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +    fun onTick(event: LorenzTickEvent) {
please use TabListUpdateEvent

2024-01-18 07:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +        val index = tabList.indexOfFirst { headerPattern.matches(it) }
this could be just one line with an elvis operator. Something like:
`val index = tabList.indexOfFirst { headerPattern.matches(it) } ?: return`

2024-01-18 07:13 UTC, CalMWolfs commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +    private fun isEnabled() = LorenzUtils.inSkyBlock && IslandType.CRIMSON_ISLE.isInIsland() && config.volcanoExplosivity
isInIsland already checks for if they are in skyblock

2024-01-18 14:28 UTC, RayDeeUx commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +        val index = tabList.indexOfFirst { headerPattern.matches(it) }
adapted from intellij:
```kt
public inline fun <T> List<T>.indexOfFirst(
    predicate: (T) -> Boolean
): Int
// Returns index of the first element matching the given predicate, or -1 if the list does not contain such element.
```
can't really use elvis on a function that can't return null :I

2024-01-18 14:28 UTC, RayDeeUx commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +    private fun isEnabled() = LorenzUtils.inSkyBlock && IslandType.CRIMSON_ISLE.isInIsland() && config.volcanoExplosivity
done

2024-01-18 14:29 UTC, RayDeeUx commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +    fun onTick(event: LorenzTickEvent) {
done

2024-01-18 14:29 UTC, RayDeeUx commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +    @SubscribeEvent
added empty line

2024-01-18 15:11 UTC, nea89o requested changes

2024-01-18 15:11 UTC, nea89o commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +        statusPattern.matchMatcher(tabList[tabList.indexOfFirst { headerPattern.matches(it) } + 1]) {
Currently you iterate over `tabList` twice. Also if the the last line of the tablist matches the header this crashes.

```suggestion
        val headerIndex = tabList.indexOfFirst { headerPattern.matches(it) }
        if (headerIndex < 0 || headerIndex + 1 !in tabList.indices) return
        statusPattern.matchMatcher(tabList[headerIndex + 1]) {
```

2024-01-18 19:52 UTC, CalMWolfs approved these changes

2024-01-18 20:30 UTC, nea89o approved these changes

2024-01-19 17:50 UTC, Thunderblade73 approved these changes

2024-01-20 10:39 UTC, hannibal002 commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +        val headerIndex = tabList.indexOfFirst { headerPattern.matches(it) }
Use this instead:
```
val text = event.tabList.nextAfter({ headerPattern.matches(it) }) ?: return
statusPattern.matchMatcher(text) {
```

2024-01-20 13:14 UTC, RayDeeUx commented on src/main/java/at/hannibal2/skyhanni/features/nether/VolcanoExplosivityDisplay.kt
> +        val headerIndex = tabList.indexOfFirst { headerPattern.matches(it) }
done

2024-01-21 10:10 UTC, hannibal002 approved these changes

2024-01-21 10:10 UTC, merged